// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RzR.DataVigil.Storage.EfSqlServer;

namespace RzR.DataVigil.Storage.EfSqlServer.Migrations
{
    [DbContext(typeof(AuditSqlServerDbContext))]
    [Migration("20260829075916_WidenAuditTransactionQueryIndexes")]
    partial class WidenAuditTransactionQueryIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityTypeName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "Action")
                        .HasDatabaseName("IX_AuditEntries_EntityName");

                    b.HasIndex("TransactionId", "Action")
                        .HasDatabaseName("IX_AuditEntries_TransactionId");

                    b.ToTable("AuditEntries", "audit");
                });

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.AuditEntryProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuditEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuditEntryId");

                    b.ToTable("AuditEntryProperties", "audit");
                });

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.AuditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("GdprState")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TraceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "Id");

                    b.HasIndex("CorrelationId", "Timestamp", "Id");

                    b.HasIndex("GdprState", "Timestamp", "Id");

                    b.HasIndex("UserId", "Timestamp", "Id");

                    b.ToTable("AuditTransactions", "audit");
                });

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.Referees.RefAuditAction", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RefAuditActions", "audit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A new entity was inserted.",
                            Name = "Create"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An existing entity was read.",
                            Name = "Read"
                        },
                        new
                        {
                            Id = 3,
                            Description = "An existing entity was modified.",
                            Name = "Update"
                        },
                        new
                        {
                            Id = 4,
                            Description = "An existing entity was deleted.",
                            Name = "Delete"
                        });
                });

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.Referees.RefAuditUserSource", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RefAuditUserSources", "audit");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Resolver returned a user but did not declare where that identity came from. The recorded actor is real and can be trusted; only its provenance is undeclared. Contrast with Unresolved, where attribution itself failed.",
                            Name = "Unspecified"
                        },
                        new
                        {
                            Id = 1,
                            Description = "No resolver could be consulted or resolution failed; attribution is unknown.",
                            Name = "Unresolved"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Resolution succeeded and there is genuinely no user for this action.",
                            Name = "Anonymous"
                        },
                        new
                        {
                            Id = 3,
                            Description = "User taken from an IAuditScopeContext manual override.",
                            Name = "ScopeContext"
                        },
                        new
                        {
                            Id = 4,
                            Description = "User extracted from the ASP.NET Core HttpContext authenticated principal.",
                            Name = "HttpContext"
                        },
                        new
                        {
                            Id = 5,
                            Description = "User extracted from Thread.CurrentPrincipal.",
                            Name = "ThreadPrincipal"
                        });
                });

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.Referees.RefGdprFieldAction", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RefGdprFieldActions", "audit");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Field is not stored or displayed at all.",
                            Name = "Exclude"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Field is partially hidden, for example j***@mail.com.",
                            Name = "Mask"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Field is fully replaced with an anonymized placeholder.",
                            Name = "Anonymize"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Field is replaced with a SHA-256 hash for pseudonymization.",
                            Name = "Hash"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Field is transformed by a custom delegate.",
                            Name = "Custom"
                        });
                });

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.Referees.RefGdprStorageState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RefGdprStorageStates", "audit");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Data is stored unmodified.",
                            Name = "Original"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Some fields have been masked, hashed or otherwise processed.",
                            Name = "PartiallyProcessed"
                        },
                        new
                        {
                            Id = 2,
                            Description = "All sensitive data has been fully anonymized.",
                            Name = "FullyAnonymized"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Data has been erased under right-to-erasure.",
                            Name = "Erased"
                        });
                });

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.AuditEntry", b =>
                {
                    b.HasOne("RzR.DataVigil.Abstractions.Models.Entries.AuditTransaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.AuditEntryProperty", b =>
                {
                    b.HasOne("RzR.DataVigil.Abstractions.Models.Entries.AuditEntry", null)
                        .WithMany("Properties")
                        .HasForeignKey("AuditEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.AuditEntry", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RzR.DataVigil.Abstractions.Models.Entries.AuditTransaction", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
