<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>disable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\code\RzR.DataVigil.Core\RzR.DataVigil.Core.csproj" />
		<ProjectReference Include="..\..\code\RzR.DataVigil.Abstractions\RzR.DataVigil.Abstractions.csproj" />
		<ProjectReference Include="..\..\code\storage\RzR.DataVigil.Storage.File\RzR.DataVigil.Storage.File.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Stores\" />
	</ItemGroup>

</Project>